### ISSUE TITLE
Add .gitignore for *.pyc files

### ISSUE THREAD

**Issue by italic-r** [kinoraw/kinoraw_tools#1]
Hi there. We included your repository as a submodule in https://github.com/meta-androcto/blenderpython/tree/ita_submodules/scripts/addons_extern and it would be fantastic if you could add *.pyc or **pycache** to your ignore file. This will keep not only our repo clean, but yours and anybody else's working on it. 

Cheers! And happy blending!

**Comment by ghost** [comment]
It was included: *pyc in gitignore :) https://github.com/kinoraw/kinoraw_tools/commit/2e12668562e447e2c9c1508172fbf2ef34be4e6c
