### ISSUE TITLE
still developing this?

### ISSUE THREAD

**Issue by meta-androcto** [kinoraw/kinoraw_tools#3]
hi, are you still developing this? I'm updating addons for Blender 2.79
time is very short.
thanks.

**Comment by surreal6** [comment]
yes, i'm interested in maintain it.
Lately I didn't used the addon, so I'm not sure if all the features are still working, but main functions are.

**Comment by meta-androcto** [comment]
hi, sounds good, how to proceed? can you run test & let me know.
I noticed the addons of yours in addons contrib & want to update & add to 2.79 release as we have no vse addons in release. I will create tast in Tracker & tag you there.
Thanks.
I'll be in irc freenode #blenderpython if you can drop in for chat there would be great.
Thanks again. Brendon.

**Comment by meta-androcto** [comment]
hi, I need to move forward here as bcon3 ( bug fix tidy up ) is coming soon, thanks,
I would put kinoraw tools in blender 2.79 release asap.
If you could drop intio irc freenode #blenderpython for quick chat would be good too.

**Comment by surreal6** [comment]
hi there, i tested the addon with blender 2.78c and it is working fine. I removed a dependencies involving another addon (quickfunctions) becouse i decided not to mantain the shortcut panel for this addon (as it becomes bigger and very complete...)

There are some panel that are experimental (the glitch one...) and will only work in linux with some dependencies. 

I have a few functions that will be deprecated like the ones involving proxies as this functions are now present natively in blender, but this will happen in the next months, not just now.

Not sure what else you need for me to do...  i'll try to connect to the irc this afternoon...

Ah, i found two tasks in the phabricator but not sure what to do with...    also you mention carlos paredes in the same task and i think it is a mistake, don't know who is carlos paredes, i'm carlos Padial, thought you mistake the surnames :P

**Comment by meta-androcto** [comment]
Hi thanks for fast response, I've edited task (was auto getting the name..)
https://developer.blender.org/T51109
If you can comment in the task we can move conversation.
Also you can drag drop the current file in zip into the comments, 
Are you familiar with blender git? Once we look at addon, maybe request a couple of changes, it would be good for you to commit to release.
We hope to solve this very quickly *sorry for urgency as blender 2.79 bcon3 is only a week away & we would like to have addons complete.
Thanks.
